// To parse this JSON data, do
//
//     final doModel = doModelFromJson(jsonString);

import 'dart:convert';

List<DoModel> doModelFromJson(String str) =>
    List<DoModel>.from(json.decode(str).map((x) => DoModel.fromJson(x)));

String doModelToJson(List<DoModel> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class DoModel {
  DoModel({
    required this.xtsoname,
    required this.dsmname,
    required this.asmname,
    required this.orgname,
    required this.dornum,
    required this.xdate,
    required this.xdatedel,
    required this.xcus,
    required this.xorg,
    required this.xpaymentterm,
    required this.xwh,
    required this.xwhdesc,
    required this.xsubcat,
    required this.xpaymenttype,
    required this.xdistrictop,
    required this.xthanaop,
    required this.preparer,
    required this.designation,
    required this.deptname,
    required this.signname,
    required this.signdesignation,
    required this.signdeptname,
    required this.ztime,
    required this.zutime,
    required this.zauserid,
    required this.zuuserid,
    required this.zid,
    required this.xdornum,
    required this.xstatusord,
    required this.xref,
    required this.xnote,
    required this.xpornum,
    required this.xstatusar,
    required this.xtotamt,
    required this.xdisc,
    required this.xdiscf,
    required this.xdatecom,
    required this.xait,
    required this.xamount,
    required this.xvatrate,
    required this.xdatedue,
    required this.xavlperc,
    required this.xsp,
    required this.xpp,
    required this.xvatamt,
    required this.xaitamt,
    required this.xdiscamt,
    required this.xfm,
    required this.xsm,
    required this.xrsm,
    required this.xterritory,
    required this.xfield,
    required this.xregion,
    required this.xarea,
    required this.xdoctype,
    required this.xproject,
    required this.xyear,
    required this.xper,
    required this.xmarket,
    required this.xtype,
    required this.xroute,
    required this.xstatus,
    required this.xprime,
    required this.xdatepo,
    required this.xdeltime,
    required this.xsumnum,
    required this.xcrnnum,
    required this.xexpamt,
    required this.xnetamt,
    required this.xnetret,
    required this.xstatusdor,
    required this.xordernum,
    required this.xvoucher,
    required this.xadamount,
    required this.xtaxrate,
    required this.xtaxamt,
    required this.xcomm,
    required this.xcomm1,
    required this.xcomm2,
    required this.xcomm3,
    required this.xnote1,
    required this.xnote2,
    required this.xnote3,
    required this.xassessval,
    required this.xassessval1,
    required this.xassessval2,
    required this.xassessval3,
    required this.xcommin,
    required this.xsuperiorsp,
    required this.xpreparer,
    required this.xdphead,
    required this.xcheaker,
    required this.xmanager,
    required this.xcpo,
    required this.xgmdf,
    required this.xed,
    required this.xdmddc,
    required this.xdatechk,
    required this.xdatedph,
    required this.xdatecpo,
    required this.xdatemanager,
    required this.xdategm,
    required this.xdatedf,
    required this.xdateed,
    required this.xdatedmddc,
    required this.xfwh,
    required this.xstatusjv,
    required this.zemail,
    required this.xcur,
    required this.xexch,
    required this.xcrterms,
    required this.xctype,
    required this.xcrdcardno,
    required this.xbank,
    required this.xpaid,
    required this.xbillno,
    required this.xlong,
    required this.xvatf,
    required this.xaitf,
    required this.xperson,
    required this.xpaystatus,
    required this.xcardtype,
    required this.xchgscard,
    required this.xchgsamt,
    required this.xserialall,
    required this.xgiftvoucher,
    required this.xvoucheramt,
    required this.xpromono,
    required this.xbonuspoints,
    required this.xearnedbonuspoints,
    required this.xphone,
    required this.xearnedbonusamt,
    required this.xissuebank,
    required this.xpaytype,
    required this.xcrnamt,
    required this.xcashamt,
    required this.xcardamt,
    required this.xspdiscamt,
    required this.xstatusprint,
    required this.xcardno,
    required this.xrptcount,
    required this.xadvat,
    required this.xadtax,
    required this.xsignatory1,
    required this.xsigndate1,
    required this.xsignatory2,
    required this.xsigndate2,
    required this.xsignatory3,
    required this.xsigndate3,
    required this.xsignatory4,
    required this.xsigndate4,
    required this.xsignatory5,
    required this.xsigndate5,
    required this.xsignatory6,
    required this.xsigndate6,
    required this.xsignatory7,
    required this.xsigndate7,
    required this.xidsup,
    required this.xsuperior2,
    required this.xsuperior3,
    required this.xsignreject,
    required this.xdatereject,
    required this.xporeqnum,
    required this.xstatusap,
    required this.xvatstatus,
    required this.xstaff,
    required this.xstatusdc,
    required this.xtso,
    required this.xmadd,
    required this.xtornum,
    required this.xdateso,
    required this.xinterestamt,
    required this.xquotref,
    required this.xregcost,
    required this.xrefstaff,
    required this.xqotnum,
    required this.xstatuscrn,
    required this.xtordate,
    required this.zactive,
    required this.xtypedo,
    required this.xdealer,
    required this.xinstallment,
    required this.xdateeff,
    required this.xchange,
    required this.xdriver,
    required this.xtruckno,
    required this.xfinancer,
    required this.xinterest,
    required this.xdaterec,
    required this.xstatusrec,
    required this.xgtotal,
    required this.xbalprime,
    required this.xstype,
    required this.xemiamt,
    required this.xregifor,
    required this.xchecker,
    required this.xmobile,
    required this.xdatedelregi,
    required this.xdiscamtregi,
    required this.xadamountregi,
    required this.xvatamttregi,
    required this.xdateregi,
    required this.xstatusordregi,
    required this.xrem,
    required this.xdivisionop,
  });

  dynamic xtsoname;
  dynamic dsmname;
  dynamic asmname;
  dynamic orgname;
  dynamic dornum;
  Xdate xdate;
  Xdate xdatedel;
  dynamic xcus;
  dynamic xorg;
  dynamic xpaymentterm;
  dynamic xwh;
  dynamic xwhdesc;
  dynamic xsubcat;
  dynamic xpaymenttype;
  dynamic xdistrictop;
  dynamic xthanaop;
  dynamic preparer;
  dynamic designation;
  dynamic deptname;
  dynamic signname;
  dynamic signdesignation;
  dynamic signdeptname;
  Xdate ztime;
  dynamic zutime;
  dynamic zauserid;
  dynamic zuuserid;
  int zid;
  dynamic xdornum;
  dynamic xstatusord;
  dynamic xref;
  dynamic xnote;
  dynamic xpornum;
  dynamic xstatusar;
  dynamic xtotamt;
  dynamic xdisc;
  dynamic xdiscf;
  Xdate xdatecom;
  dynamic xait;
  dynamic xamount;
  dynamic xvatrate;
  Xdate xdatedue;
  dynamic xavlperc;
  dynamic xsp;
  dynamic xpp;
  dynamic xvatamt;
  dynamic xaitamt;
  dynamic xdiscamt;
  dynamic xfm;
  dynamic xsm;
  dynamic xrsm;
  dynamic xterritory;
  dynamic xfield;
  dynamic xregion;
  dynamic xarea;
  dynamic xdoctype;
  dynamic xproject;
  int xyear;
  int xper;
  dynamic xmarket;
  dynamic xtype;
  dynamic xroute;
  dynamic xstatus;
  dynamic xprime;
  Xdate xdatepo;
  dynamic xdeltime;
  dynamic xsumnum;
  dynamic xcrnnum;
  dynamic xexpamt;
  dynamic xnetamt;
  dynamic xnetret;
  dynamic xstatusdor;
  dynamic xordernum;
  dynamic xvoucher;
  dynamic xadamount;
  dynamic xtaxrate;
  dynamic xtaxamt;
  dynamic xcomm;
  dynamic xcomm1;
  dynamic xcomm2;
  dynamic xcomm3;
  dynamic xnote1;
  dynamic xnote2;
  dynamic xnote3;
  dynamic xassessval;
  dynamic xassessval1;
  dynamic xassessval2;
  dynamic xassessval3;
  dynamic xcommin;
  dynamic xsuperiorsp;
  dynamic xpreparer;
  dynamic xdphead;
  dynamic xcheaker;
  dynamic xmanager;
  dynamic xcpo;
  dynamic xgmdf;
  dynamic xed;
  dynamic xdmddc;
  Xdate xdatechk;
  dynamic xdatedph;
  dynamic xdatecpo;
  dynamic xdatemanager;
  dynamic xdategm;
  dynamic xdatedf;
  dynamic xdateed;
  dynamic xdatedmddc;
  dynamic xfwh;
  dynamic xstatusjv;
  dynamic zemail;
  dynamic xcur;
  dynamic xexch;
  dynamic xcrterms;
  dynamic xctype;
  dynamic xcrdcardno;
  dynamic xbank;
  dynamic xpaid;
  dynamic xbillno;
  dynamic xlong;
  dynamic xvatf;
  dynamic xaitf;
  dynamic xperson;
  dynamic xpaystatus;
  dynamic xcardtype;
  dynamic xchgscard;
  dynamic xchgsamt;
  dynamic xserialall;
  dynamic xgiftvoucher;
  dynamic xvoucheramt;
  dynamic xpromono;
  dynamic xbonuspoints;
  dynamic xearnedbonuspoints;
  dynamic xphone;
  dynamic xearnedbonusamt;
  dynamic xissuebank;
  dynamic xpaytype;
  dynamic xcrnamt;
  dynamic xcashamt;
  dynamic xcardamt;
  dynamic xspdiscamt;
  dynamic xstatusprint;
  dynamic xcardno;
  dynamic xrptcount;
  dynamic xadvat;
  dynamic xadtax;
  dynamic xsignatory1;
  dynamic xsigndate1;
  dynamic xsignatory2;
  dynamic xsigndate2;
  dynamic xsignatory3;
  dynamic xsigndate3;
  dynamic xsignatory4;
  dynamic xsigndate4;
  dynamic xsignatory5;
  dynamic xsigndate5;
  dynamic xsignatory6;
  dynamic xsigndate6;
  dynamic xsignatory7;
  dynamic xsigndate7;
  dynamic xidsup;
  dynamic xsuperior2;
  dynamic xsuperior3;
  dynamic xsignreject;
  dynamic xdatereject;
  dynamic xporeqnum;
  dynamic xstatusap;
  dynamic xvatstatus;
  dynamic xstaff;
  dynamic xstatusdc;
  dynamic xtso;
  dynamic xmadd;
  dynamic xtornum;
  Xdate xdateso;
  dynamic xinterestamt;
  dynamic xquotref;
  dynamic xregcost;
  dynamic xrefstaff;
  dynamic xqotnum;
  dynamic xstatuscrn;
  Xdate xtordate;
  dynamic zactive;
  dynamic xtypedo;
  dynamic xdealer;
  dynamic xinstallment;
  dynamic xdateeff;
  dynamic xchange;
  dynamic xdriver;
  dynamic xtruckno;
  dynamic xfinancer;
  dynamic xinterest;
  dynamic xdaterec;
  dynamic xstatusrec;
  dynamic xgtotal;
  dynamic xbalprime;
  dynamic xstype;
  dynamic xemiamt;
  dynamic xregifor;
  dynamic xchecker;
  dynamic xmobile;
  dynamic xdatedelregi;
  dynamic xdiscamtregi;
  dynamic xadamountregi;
  dynamic xvatamttregi;
  dynamic xdateregi;
  dynamic xstatusordregi;
  dynamic xrem;
  dynamic xdivisionop;

  factory DoModel.fromJson(Map<String, dynamic> json) => DoModel(
        xtsoname: json["xtsoname"],
        dsmname: json["dsmname"],
        asmname: json["asmname"],
        orgname: json["orgname"],
        dornum: json["dornum"],
        xdate: Xdate.fromJson(json["xdate"]),
        xdatedel: Xdate.fromJson(json["xdatedel"]),
        xcus: json["xcus"],
        xorg: json["xorg"],
        xpaymentterm: json["xpaymentterm"],
        xwh: json["xwh"],
        xwhdesc: json["xwhdesc"],
        xsubcat: json["xsubcat"],
        xpaymenttype: json["xpaymenttype"],
        xdistrictop: json["xdistrictop"],
        xthanaop: json["xthanaop"],
        preparer: json["preparer"] == null ? null : json["preparer"],
        designation: json["designation"] == null ? null : json["designation"],
        deptname: json["deptname"] == null ? null : json["deptname"],
        signname: json["signname"] == null ? null : json["signname"],
        signdesignation:
            json["signdesignation"] == null ? null : json["signdesignation"],
        signdeptname:
            json["signdeptname"] == null ? null : json["signdeptname"],
        ztime: Xdate.fromJson(json["ztime"]),
        zutime: Xdate.fromJson(json["zutime"]),
        zauserid: json["zauserid"],
        zuuserid: json["zuuserid"],
        zid: json["zid"],
        xdornum: json["xdornum"],
        xstatusord: json["xstatusord"],
        xref: json["xref"],
        xnote: json["xnote"],
        xpornum: json["xpornum"],
        xstatusar: json["xstatusar"],
        xtotamt: json["xtotamt"],
        xdisc: json["xdisc"],
        xdiscf: json["xdiscf"],
        xdatecom: Xdate.fromJson(json["xdatecom"]),
        xait: json["xait"],
        xamount: json["xamount"],
        xvatrate: json["xvatrate"],
        xdatedue: Xdate.fromJson(json["xdatedue"]),
        xavlperc: json["xavlperc"],
        xsp: json["xsp"],
        xpp: json["xpp"],
        xvatamt: json["xvatamt"],
        xaitamt: json["xaitamt"],
        xdiscamt: json["xdiscamt"],
        xfm: json["xfm"],
        xsm: json["xsm"],
        xrsm: json["xrsm"],
        xterritory: json["xterritory"],
        xfield: json["xfield"],
        xregion: json["xregion"],
        xarea: json["xarea"],
        xdoctype: json["xdoctype"],
        xproject: json["xproject"],
        xyear: json["xyear"],
        xper: json["xper"],
        xmarket: json["xmarket"],
        xtype: json["xtype"],
        xroute: json["xroute"],
        xstatus: json["xstatus"],
        xprime: json["xprime"],
        xdatepo: Xdate.fromJson(json["xdatepo"]),
        xdeltime: json["xdeltime"],
        xsumnum: json["xsumnum"],
        xcrnnum: json["xcrnnum"],
        xexpamt: json["xexpamt"],
        xnetamt: json["xnetamt"],
        xnetret: json["xnetret"],
        xstatusdor: json["xstatusdor"],
        xordernum: json["xordernum"],
        xvoucher: json["xvoucher"],
        xadamount: json["xadamount"],
        xtaxrate: json["xtaxrate"],
        xtaxamt: json["xtaxamt"],
        xcomm: json["xcomm"],
        xcomm1: json["xcomm1"],
        xcomm2: json["xcomm2"],
        xcomm3: json["xcomm3"],
        xnote1: json["xnote1"] == null ? null : json["xnote1"],
        xnote2: json["xnote2"],
        xnote3: json["xnote3"],
        xassessval: json["xassessval"],
        xassessval1: json["xassessval1"],
        xassessval2: json["xassessval2"],
        xassessval3: json["xassessval3"],
        xcommin: json["xcommin"],
        xsuperiorsp: json["xsuperiorsp"],
        xpreparer: json["xpreparer"],
        xdphead: json["xdphead"],
        xcheaker: json["xcheaker"],
        xmanager: json["xmanager"],
        xcpo: json["xcpo"],
        xgmdf: json["xgmdf"],
        xed: json["xed"],
        xdmddc: json["xdmddc"],
        xdatechk: Xdate.fromJson(json["xdatechk"]),
        xdatedph: json["xdatedph"],
        xdatecpo: json["xdatecpo"],
        xdatemanager: json["xdatemanager"],
        xdategm: json["xdategm"],
        xdatedf: json["xdatedf"],
        xdateed: json["xdateed"],
        xdatedmddc: json["xdatedmddc"],
        xfwh: json["xfwh"],
        xstatusjv: json["xstatusjv"],
        zemail: json["zemail"],
        xcur: json["xcur"],
        xexch: json["xexch"],
        xcrterms: json["xcrterms"],
        xctype: json["xctype"],
        xcrdcardno: json["xcrdcardno"],
        xbank: json["xbank"],
        xpaid: json["xpaid"],
        xbillno: json["xbillno"],
        xlong: json["xlong"],
        xvatf: json["xvatf"],
        xaitf: json["xaitf"],
        xperson: json["xperson"],
        xpaystatus: json["xpaystatus"],
        xcardtype: json["xcardtype"],
        xchgscard: json["xchgscard"],
        xchgsamt: json["xchgsamt"],
        xserialall: json["xserialall"],
        xgiftvoucher: json["xgiftvoucher"],
        xvoucheramt: json["xvoucheramt"],
        xpromono: json["xpromono"],
        xbonuspoints: json["xbonuspoints"],
        xearnedbonuspoints: json["xearnedbonuspoints"],
        xphone: json["xphone"],
        xearnedbonusamt: json["xearnedbonusamt"],
        xissuebank: json["xissuebank"],
        xpaytype: json["xpaytype"],
        xcrnamt: json["xcrnamt"],
        xcashamt: json["xcashamt"],
        xcardamt: json["xcardamt"],
        xspdiscamt: json["xspdiscamt"],
        xstatusprint: json["xstatusprint"],
        xcardno: json["xcardno"],
        xrptcount: json["xrptcount"],
        xadvat: json["xadvat"],
        xadtax: json["xadtax"],
        xsignatory1: json["xsignatory1"],
        xsigndate1: json["xsigndate1"],
        xsignatory2: json["xsignatory2"] == null ? null : json["xsignatory2"],
        xsigndate2: json["xsigndate2"],
        xsignatory3: json["xsignatory3"] == null ? null : json["xsignatory3"],
        xsigndate3: json["xsigndate3"],
        xsignatory4: json["xsignatory4"] == null ? null : json["xsignatory4"],
        xsigndate4: json["xsigndate4"],
        xsignatory5: json["xsignatory5"] == null ? null : json["xsignatory5"],
        xsigndate5: json["xsigndate5"],
        xsignatory6: json["xsignatory6"] == null ? null : json["xsignatory6"],
        xsigndate6: json["xsigndate6"],
        xsignatory7: json["xsignatory7"] == null ? null : json["xsignatory7"],
        xsigndate7: json["xsigndate7"],
        xidsup: json["xidsup"] == null ? null : json["xidsup"],
        xsuperior2: json["xsuperior2"],
        xsuperior3: json["xsuperior3"],
        xsignreject: json["xsignreject"] == null ? null : json["xsignreject"],
        xdatereject: json["xdatereject"],
        xporeqnum: json["xporeqnum"],
        xstatusap: json["xstatusap"],
        xvatstatus: json["xvatstatus"],
        xstaff: json["xstaff"],
        xstatusdc: json["xstatusdc"],
        xtso: json["xtso"],
        xmadd: json["xmadd"],
        xtornum: json["xtornum"],
        xdateso: Xdate.fromJson(json["xdateso"]),
        xinterestamt: json["xinterestamt"],
        xquotref: json["xquotref"],
        xregcost: json["xregcost"],
        xrefstaff: json["xrefstaff"],
        xqotnum: json["xqotnum"],
        xstatuscrn: json["xstatuscrn"],
        xtordate: Xdate.fromJson(json["xtordate"]),
        zactive: json["zactive"],
        xtypedo: json["xtypedo"],
        xdealer: json["xdealer"],
        xinstallment: json["xinstallment"],
        xdateeff: json["xdateeff"],
        xchange: json["xchange"],
        xdriver: json["xdriver"],
        xtruckno: json["xtruckno"],
        xfinancer: json["xfinancer"],
        xinterest: json["xinterest"],
        xdaterec: json["xdaterec"],
        xstatusrec: json["xstatusrec"],
        xgtotal: json["xgtotal"],
        xbalprime: json["xbalprime"],
        xstype: json["xstype"],
        xemiamt: json["xemiamt"],
        xregifor: json["xregifor"],
        xchecker: json["xchecker"],
        xmobile: json["xmobile"],
        xdatedelregi: json["xdatedelregi"],
        xdiscamtregi: json["xdiscamtregi"],
        xadamountregi: json["xadamountregi"],
        xvatamttregi: json["xvatamttregi"],
        xdateregi: json["xdateregi"],
        xstatusordregi: json["xstatusordregi"],
        xrem: json["xrem"],
        xdivisionop: json["xdivisionop"],
      );

  Map<String, dynamic> toJson() => {
        "xtsoname": xtsoname,
        "dsmname": dsmname,
        "asmname": asmname,
        "orgname": orgname,
        "dornum": dornum,
        "xdate": xdate.toJson(),
        "xdatedel": xdatedel.toJson(),
        "xcus": xcus,
        "xorg": xorg,
        "xpaymentterm": xpaymentterm,
        "xwh": xwh,
        "xwhdesc": xwhdesc,
        "xsubcat": xsubcat,
        "xpaymenttype": xpaymenttype,
        "xdistrictop": xdistrictop,
        "xthanaop": xthanaop,
        "preparer": preparer == null ? null : preparer,
        "designation": designation == null ? null : designation,
        "deptname": deptname == null ? null : deptname,
        "signname": signname == null ? null : signname,
        "signdesignation": signdesignation == null ? null : signdesignation,
        "signdeptname": signdeptname == null ? null : signdeptname,
        "ztime": ztime.toJson(),
        "zutime": zutime.toJson(),
        "zauserid": zauserid,
        "zuuserid": zuuserid,
        "zid": zid,
        "xdornum": xdornum,
        "xstatusord": xstatusord,
        "xref": xref,
        "xnote": xnote,
        "xpornum": xpornum,
        "xstatusar": xstatusar,
        "xtotamt": xtotamt,
        "xdisc": xdisc,
        "xdiscf": xdiscf,
        "xdatecom": xdatecom.toJson(),
        "xait": xait,
        "xamount": xamount,
        "xvatrate": xvatrate,
        "xdatedue": xdatedue.toJson(),
        "xavlperc": xavlperc,
        "xsp": xsp,
        "xpp": xpp,
        "xvatamt": xvatamt,
        "xaitamt": xaitamt,
        "xdiscamt": xdiscamt,
        "xfm": xfm,
        "xsm": xsm,
        "xrsm": xrsm,
        "xterritory": xterritory,
        "xfield": xfield,
        "xregion": xregion,
        "xarea": xarea,
        "xdoctype": xdoctype,
        "xproject": xproject,
        "xyear": xyear,
        "xper": xper,
        "xmarket": xmarket,
        "xtype": xtype,
        "xroute": xroute,
        "xstatus": xstatus,
        "xprime": xprime,
        "xdatepo": xdatepo.toJson(),
        "xdeltime": xdeltime,
        "xsumnum": xsumnum,
        "xcrnnum": xcrnnum,
        "xexpamt": xexpamt,
        "xnetamt": xnetamt,
        "xnetret": xnetret,
        "xstatusdor": xstatusdor,
        "xordernum": xordernum,
        "xvoucher": xvoucher,
        "xadamount": xadamount,
        "xtaxrate": xtaxrate,
        "xtaxamt": xtaxamt,
        "xcomm": xcomm,
        "xcomm1": xcomm1,
        "xcomm2": xcomm2,
        "xcomm3": xcomm3,
        "xnote1": xnote1 == null ? null : xnote1,
        "xnote2": xnote2,
        "xnote3": xnote3,
        "xassessval": xassessval,
        "xassessval1": xassessval1,
        "xassessval2": xassessval2,
        "xassessval3": xassessval3,
        "xcommin": xcommin,
        "xsuperiorsp": xsuperiorsp,
        "xpreparer": xpreparer,
        "xdphead": xdphead,
        "xcheaker": xcheaker,
        "xmanager": xmanager,
        "xcpo": xcpo,
        "xgmdf": xgmdf,
        "xed": xed,
        "xdmddc": xdmddc,
        "xdatechk": xdatechk.toJson(),
        "xdatedph": xdatedph,
        "xdatecpo": xdatecpo,
        "xdatemanager": xdatemanager,
        "xdategm": xdategm,
        "xdatedf": xdatedf,
        "xdateed": xdateed,
        "xdatedmddc": xdatedmddc,
        "xfwh": xfwh,
        "xstatusjv": xstatusjv,
        "zemail": zemail,
        "xcur": xcur,
        "xexch": xexch,
        "xcrterms": xcrterms,
        "xctype": xctype,
        "xcrdcardno": xcrdcardno,
        "xbank": xbank,
        "xpaid": xpaid,
        "xbillno": xbillno,
        "xlong": xlong,
        "xvatf": xvatf,
        "xaitf": xaitf,
        "xperson": xperson,
        "xpaystatus": xpaystatus,
        "xcardtype": xcardtype,
        "xchgscard": xchgscard,
        "xchgsamt": xchgsamt,
        "xserialall": xserialall,
        "xgiftvoucher": xgiftvoucher,
        "xvoucheramt": xvoucheramt,
        "xpromono": xpromono,
        "xbonuspoints": xbonuspoints,
        "xearnedbonuspoints": xearnedbonuspoints,
        "xphone": xphone,
        "xearnedbonusamt": xearnedbonusamt,
        "xissuebank": xissuebank,
        "xpaytype": xpaytype,
        "xcrnamt": xcrnamt,
        "xcashamt": xcashamt,
        "xcardamt": xcardamt,
        "xspdiscamt": xspdiscamt,
        "xstatusprint": xstatusprint,
        "xcardno": xcardno,
        "xrptcount": xrptcount,
        "xadvat": xadvat,
        "xadtax": xadtax,
        "xsignatory1": xsignatory1,
        "xsigndate1": xsigndate1 == null ? null : xsigndate1.toJson(),
        "xsignatory2": xsignatory2 == null ? null : xsignatory2,
        "xsigndate2": xsigndate2,
        "xsignatory3": xsignatory3 == null ? null : xsignatory3,
        "xsigndate3": xsigndate3,
        "xsignatory4": xsignatory4 == null ? null : xsignatory4,
        "xsigndate4": xsigndate4,
        "xsignatory5": xsignatory5 == null ? null : xsignatory5,
        "xsigndate5": xsigndate5,
        "xsignatory6": xsignatory6 == null ? null : xsignatory6,
        "xsigndate6": xsigndate6,
        "xsignatory7": xsignatory7 == null ? null : xsignatory7,
        "xsigndate7": xsigndate7,
        "xidsup": xidsup == null ? null : xidsup,
        "xsuperior2": xsuperior2,
        "xsuperior3": xsuperior3,
        "xsignreject": xsignreject == null ? null : xsignreject,
        "xdatereject": xdatereject == null ? null : xdatereject.toJson(),
        "xporeqnum": xporeqnum,
        "xstatusap": xstatusap,
        "xvatstatus": xvatstatus,
        "xstaff": xstaff,
        "xstatusdc": xstatusdc,
        "xtso": xtso,
        "xmadd": xmadd,
        "xtornum": xtornum,
        "xdateso": xdateso.toJson(),
        "xinterestamt": xinterestamt,
        "xquotref": xquotref,
        "xregcost": xregcost,
        "xrefstaff": xrefstaff,
        "xqotnum": xqotnum,
        "xstatuscrn": xstatuscrn,
        "xtordate": xtordate.toJson(),
        "zactive": zactive,
        "xtypedo": xtypedo,
        "xdealer": xdealer,
        "xinstallment": xinstallment,
        "xdateeff": xdateeff,
        "xchange": xchange,
        "xdriver": xdriver,
        "xtruckno": xtruckno,
        "xfinancer": xfinancer,
        "xinterest": xinterest,
        "xdaterec": xdaterec,
        "xstatusrec": xstatusrec,
        "xgtotal": xgtotal,
        "xbalprime": xbalprime,
        "xstype": xstype,
        "xemiamt": xemiamt,
        "xregifor": xregifor,
        "xchecker": xchecker,
        "xmobile": xmobile,
        "xdatedelregi": xdatedelregi,
        "xdiscamtregi": xdiscamtregi,
        "xadamountregi": xadamountregi,
        "xvatamttregi": xvatamttregi,
        "xdateregi": xdateregi,
        "xstatusordregi": xstatusordregi,
        "xrem": xrem,
        "xdivisionop": xdivisionop,
      };
}

class Xdate {
  Xdate({
    required this.date,
    required this.timezoneType,
    required this.timezone,
  });

  DateTime date;
  int timezoneType;
  String timezone;

  factory Xdate.fromJson(Map<String, dynamic> json) => Xdate(
        date: DateTime.parse(json["date"]),
        timezoneType: json["timezone_type"],
        timezone: json["timezone"],
      );

  Map<String, dynamic> toJson() => {
        "date": date.toIso8601String(),
        "timezone_type": timezoneType,
        "timezone": timezone,
      };
}
