// To parse this JSON data, do
//
//     final itemsNotificationModel = itemsNotificationModelFromJson(jsonString);

import 'dart:convert';

List<ItemsNotificationModel> itemsNotificationModelFromJson(String str) =>
    List<ItemsNotificationModel>.from(
        json.decode(str).map((x) => ItemsNotificationModel.fromJson(x)));

String itemsNotificationModelToJson(List<ItemsNotificationModel> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class ItemsNotificationModel {
  ItemsNotificationModel({
    required this.ztime,
    required this.zutime,
    required this.zauserid,
    required this.zuuserid,
    required this.zid,
    required this.xitem,
    required this.xdesc,
    required this.xgitem,
    required this.xcitem,
    required this.xcatitem,
    required this.xrate,
    required this.xunitpur,
    required this.xcost,
    required this.xvatamt,
    required this.xunit,
    required this.xlong,
    required this.xtitem,
    required this.xreordlvl,
    required this.xlmax,
    required this.xlmin,
    required this.xbin,
    required this.xstype,
    required this.xalias,
    required this.xmrp,
    required this.xpacking,
    required this.xdisc,
    required this.xcartoon,
    required this.xdateeff,
    required this.xdateexp,
    required this.xspecification,
    required this.xrateexp,
    required this.xhscode,
    required this.xpackqty,
    required this.zactive,
    required this.xdiscstatus,
    required this.xbnprintstatus,
    required this.xbrand,
    required this.xcfpur,
    required this.xcfsel,
    required this.xcfiss,
    required this.xcfpck,
    required this.xunitsel,
    required this.xunitiss,
    required this.xdealerp,
    required this.xpsize,
    required this.xpnature,
    required this.xshelf,
    required this.xvatrate,
    required this.xgrade,
    required this.xminqty,
    required this.xtaxrate,
    required this.xcountry,
    required this.xtheircode,
    required this.xpartno,
    required this.xunitpck,
    required this.xmodel,
    required this.xwper,
    required this.xserialnum,
    required this.xgritem,
    required this.xserialtype,
    required this.xtype,
    required this.xcus,
    required this.xitmedept,
    required this.xitemsubdept,
    required this.xpackweightnet,
    required this.xsubcat,
    required this.xsupptaxamt,
    required this.xtypeitem,
    required this.xstocktype,
    required this.xstockcat,
    required this.xnote,
    required this.xminrate,
    required this.xmaxqty,
    required this.xvatcode,
    required this.xsubgitem,
    required this.xpclass,
    required this.xacc,
    required this.xmouza,
    required this.xbsnum,
    required this.xrsnum,
    required this.xdgnum,
    required this.xkhnum,
    required this.xqtyord,
    required this.xqtypor,
    required this.xqtyreq,
    required this.xqtyrecord,
    required this.xseller,
    required this.xproject,
    required this.xqtyop,
    required this.xtolpercent,
    required this.xsuperior2,
    required this.xsuperior3,
    required this.xpreparer,
    required this.xsignatory1,
    required this.xsigndate1,
    required this.xsignatory2,
    required this.xsigndate2,
    required this.xsignatory3,
    required this.xsigndate3,
    required this.xsignatory4,
    required this.xsigndate4,
    required this.xsignatory5,
    required this.xsigndate5,
    required this.xsignatory6,
    required this.xsigndate6,
    required this.xsignatory7,
    required this.xsuperiorsp,
    required this.xsigndate7,
    required this.xstatus,
    required this.xidsup,
    required this.xcatitemacc,
    required this.xgroupcat,
    required this.xassetitem,
    required this.xfagroup,
    required this.xfatype,
    required this.xfacat,
    required this.xprcstype,
    required this.xitemref,
    required this.xsignreject,
    required this.xdatereject,
    required this.xnote1,
    required this.xitemtype,
  });

  dynamic ztime;
  dynamic zutime;
  String zauserid;
  dynamic zuuserid;
  int zid;
  String xitem;
  String xdesc;
  String xgitem;
  String xcitem;
  String xcatitem;
  String xrate;
  String xunitpur;
  String xcost;
  String xvatamt;
  String xunit;
  String xlong;
  String xtitem;
  dynamic xreordlvl;
  dynamic xlmax;
  dynamic xlmin;
  dynamic xbin;
  String xstype;
  dynamic xalias;
  String xmrp;
  String xpacking;
  String xdisc;
  String xcartoon;
  dynamic xdateeff;
  dynamic xdateexp;
  dynamic xspecification;
  String xrateexp;
  dynamic xhscode;
  dynamic xpackqty;
  String zactive;
  String xdiscstatus;
  dynamic xbnprintstatus;
  dynamic xbrand;
  String xcfpur;
  String xcfsel;
  dynamic xcfiss;
  dynamic xcfpck;
  String xunitsel;
  dynamic xunitiss;
  String xdealerp;
  String xpsize;
  String xpnature;
  String xshelf;
  String xvatrate;
  dynamic xgrade;
  String xminqty;
  dynamic xtaxrate;
  String xcountry;
  String xtheircode;
  String xpartno;
  dynamic xunitpck;
  String xmodel;
  dynamic xwper;
  dynamic xserialnum;
  String xgritem;
  dynamic xserialtype;
  String xtype;
  dynamic xcus;
  dynamic xitmedept;
  dynamic xitemsubdept;
  dynamic xpackweightnet;
  dynamic xsubcat;
  dynamic xsupptaxamt;
  String xtypeitem;
  String xstocktype;
  String xstockcat;
  dynamic xnote;
  dynamic xminrate;
  String xmaxqty;
  dynamic xvatcode;
  dynamic xsubgitem;
  dynamic xpclass;
  dynamic xacc;
  dynamic xmouza;
  dynamic xbsnum;
  dynamic xrsnum;
  dynamic xdgnum;
  dynamic xkhnum;
  dynamic xqtyord;
  dynamic xqtypor;
  dynamic xqtyreq;
  dynamic xqtyrecord;
  dynamic xseller;
  dynamic xproject;
  dynamic xqtyop;
  dynamic xtolpercent;
  dynamic xsuperior2;
  dynamic xsuperior3;
  dynamic xpreparer;
  dynamic xsignatory1;
  dynamic xsigndate1;
  dynamic xsignatory2;
  dynamic xsigndate2;
  dynamic xsignatory3;
  dynamic xsigndate3;
  dynamic xsignatory4;
  dynamic xsigndate4;
  dynamic xsignatory5;
  dynamic xsigndate5;
  dynamic xsignatory6;
  dynamic xsigndate6;
  dynamic xsignatory7;
  dynamic xsuperiorsp;
  dynamic xsigndate7;
  dynamic xstatus;
  dynamic xidsup;
  dynamic xcatitemacc;
  dynamic xgroupcat;
  dynamic xassetitem;
  dynamic xfagroup;
  dynamic xfatype;
  dynamic xfacat;
  dynamic xprcstype;
  dynamic xitemref;
  dynamic xsignreject;
  dynamic xdatereject;
  dynamic xnote1;
  dynamic xitemtype;

  factory ItemsNotificationModel.fromJson(Map<String, dynamic> json) =>
      ItemsNotificationModel(
        ztime: json["ztime"],
        zutime: json["zutime"],
        zauserid: json["zauserid"],
        zuuserid: json["zuuserid"],
        zid: json["zid"],
        xitem: json["xitem"],
        xdesc: json["xdesc"],
        xgitem: json["xgitem"],
        xcitem: json["xcitem"],
        xcatitem: json["xcatitem"],
        xrate: json["xrate"],
        xunitpur: json["xunitpur"],
        xcost: json["xcost"],
        xvatamt: json["xvatamt"],
        xunit: json["xunit"],
        xlong: json["xlong"],
        xtitem: json["xtitem"],
        xreordlvl: json["xreordlvl"],
        xlmax: json["xlmax"],
        xlmin: json["xlmin"],
        xbin: json["xbin"],
        xstype: json["xstype"],
        xalias: json["xalias"],
        xmrp: json["xmrp"],
        xpacking: json["xpacking"],
        xdisc: json["xdisc"],
        xcartoon: json["xcartoon"],
        xdateeff: json["xdateeff"],
        xdateexp: json["xdateexp"],
        xspecification: json["xspecification"],
        xrateexp: json["xrateexp"],
        xhscode: json["xhscode"],
        xpackqty: json["xpackqty"],
        zactive: json["zactive"],
        xdiscstatus: json["xdiscstatus"],
        xbnprintstatus: json["xbnprintstatus"],
        xbrand: json["xbrand"],
        xcfpur: json["xcfpur"],
        xcfsel: json["xcfsel"],
        xcfiss: json["xcfiss"],
        xcfpck: json["xcfpck"],
        xunitsel: json["xunitsel"],
        xunitiss: json["xunitiss"],
        xdealerp: json["xdealerp"],
        xpsize: json["xpsize"],
        xpnature: json["xpnature"],
        xshelf: json["xshelf"],
        xvatrate: json["xvatrate"],
        xgrade: json["xgrade"],
        xminqty: json["xminqty"],
        xtaxrate: json["xtaxrate"],
        xcountry: json["xcountry"],
        xtheircode: json["xtheircode"],
        xpartno: json["xpartno"],
        xunitpck: json["xunitpck"],
        xmodel: json["xmodel"],
        xwper: json["xwper"],
        xserialnum: json["xserialnum"],
        xgritem: json["xgritem"],
        xserialtype: json["xserialtype"],
        xtype: json["xtype"],
        xcus: json["xcus"],
        xitmedept: json["xitmedept"],
        xitemsubdept: json["xitemsubdept"],
        xpackweightnet: json["xpackweightnet"],
        xsubcat: json["xsubcat"],
        xsupptaxamt: json["xsupptaxamt"],
        xtypeitem: json["xtypeitem"],
        xstocktype: json["xstocktype"],
        xstockcat: json["xstockcat"],
        xnote: json["xnote"],
        xminrate: json["xminrate"],
        xmaxqty: json["xmaxqty"],
        xvatcode: json["xvatcode"],
        xsubgitem: json["xsubgitem"],
        xpclass: json["xpclass"],
        xacc: json["xacc"],
        xmouza: json["xmouza"],
        xbsnum: json["xbsnum"],
        xrsnum: json["xrsnum"],
        xdgnum: json["xdgnum"],
        xkhnum: json["xkhnum"],
        xqtyord: json["xqtyord"],
        xqtypor: json["xqtypor"],
        xqtyreq: json["xqtyreq"],
        xqtyrecord: json["xqtyrecord"],
        xseller: json["xseller"],
        xproject: json["xproject"],
        xqtyop: json["xqtyop"],
        xtolpercent: json["xtolpercent"],
        xsuperior2: json["xsuperior2"],
        xsuperior3: json["xsuperior3"],
        xpreparer: json["xpreparer"],
        xsignatory1: json["xsignatory1"],
        xsigndate1: json["xsigndate1"],
        xsignatory2: json["xsignatory2"],
        xsigndate2: json["xsigndate2"],
        xsignatory3: json["xsignatory3"],
        xsigndate3: json["xsigndate3"],
        xsignatory4: json["xsignatory4"],
        xsigndate4: json["xsigndate4"],
        xsignatory5: json["xsignatory5"],
        xsigndate5: json["xsigndate5"],
        xsignatory6: json["xsignatory6"],
        xsigndate6: json["xsigndate6"],
        xsignatory7: json["xsignatory7"],
        xsuperiorsp: json["xsuperiorsp"],
        xsigndate7: json["xsigndate7"],
        xstatus: json["xstatus"],
        xidsup: json["xidsup"],
        xcatitemacc: json["xcatitemacc"],
        xgroupcat: json["xgroupcat"],
        xassetitem: json["xassetitem"],
        xfagroup: json["xfagroup"],
        xfatype: json["xfatype"],
        xfacat: json["xfacat"],
        xprcstype: json["xprcstype"],
        xitemref: json["xitemref"],
        xsignreject: json["xsignreject"],
        xdatereject: json["xdatereject"],
        xnote1: json["xnote1"],
        xitemtype: json["xitemtype"],
      );

  Map<String, dynamic> toJson() => {
        "ztime": ztime.toJson(),
        "zutime": zutime.toJson(),
        "zauserid": zauserid,
        "zuuserid": zuuserid,
        "zid": zid,
        "xitem": xitem,
        "xdesc": xdesc,
        "xgitem": xgitem,
        "xcitem": xcitem,
        "xcatitem": xcatitem,
        "xrate": xrate,
        "xunitpur": xunitpur,
        "xcost": xcost,
        "xvatamt": xvatamt,
        "xunit": xunit,
        "xlong": xlong,
        "xtitem": xtitem,
        "xreordlvl": xreordlvl,
        "xlmax": xlmax,
        "xlmin": xlmin,
        "xbin": xbin,
        "xstype": xstype,
        "xalias": xalias,
        "xmrp": xmrp,
        "xpacking": xpacking,
        "xdisc": xdisc,
        "xcartoon": xcartoon,
        "xdateeff": xdateeff,
        "xdateexp": xdateexp,
        "xspecification": xspecification,
        "xrateexp": xrateexp,
        "xhscode": xhscode,
        "xpackqty": xpackqty,
        "zactive": zactive,
        "xdiscstatus": xdiscstatus,
        "xbnprintstatus": xbnprintstatus,
        "xbrand": xbrand,
        "xcfpur": xcfpur,
        "xcfsel": xcfsel,
        "xcfiss": xcfiss,
        "xcfpck": xcfpck,
        "xunitsel": xunitsel,
        "xunitiss": xunitiss,
        "xdealerp": xdealerp,
        "xpsize": xpsize,
        "xpnature": xpnature,
        "xshelf": xshelf,
        "xvatrate": xvatrate,
        "xgrade": xgrade,
        "xminqty": xminqty,
        "xtaxrate": xtaxrate,
        "xcountry": xcountry,
        "xtheircode": xtheircode,
        "xpartno": xpartno,
        "xunitpck": xunitpck,
        "xmodel": xmodel,
        "xwper": xwper,
        "xserialnum": xserialnum,
        "xgritem": xgritem,
        "xserialtype": xserialtype,
        "xtype": xtype,
        "xcus": xcus,
        "xitmedept": xitmedept,
        "xitemsubdept": xitemsubdept,
        "xpackweightnet": xpackweightnet,
        "xsubcat": xsubcat,
        "xsupptaxamt": xsupptaxamt,
        "xtypeitem": xtypeitem,
        "xstocktype": xstocktype,
        "xstockcat": xstockcat,
        "xnote": xnote,
        "xminrate": xminrate,
        "xmaxqty": xmaxqty,
        "xvatcode": xvatcode,
        "xsubgitem": xsubgitem,
        "xpclass": xpclass,
        "xacc": xacc,
        "xmouza": xmouza,
        "xbsnum": xbsnum,
        "xrsnum": xrsnum,
        "xdgnum": xdgnum,
        "xkhnum": xkhnum,
        "xqtyord": xqtyord,
        "xqtypor": xqtypor,
        "xqtyreq": xqtyreq,
        "xqtyrecord": xqtyrecord,
        "xseller": xseller,
        "xproject": xproject,
        "xqtyop": xqtyop,
        "xtolpercent": xtolpercent,
        "xsuperior2": xsuperior2,
        "xsuperior3": xsuperior3,
        "xpreparer": xpreparer,
        "xsignatory1": xsignatory1,
        "xsigndate1": xsigndate1.toJson(),
        "xsignatory2": xsignatory2,
        "xsigndate2": xsigndate2,
        "xsignatory3": xsignatory3,
        "xsigndate3": xsigndate3,
        "xsignatory4": xsignatory4,
        "xsigndate4": xsigndate4,
        "xsignatory5": xsignatory5,
        "xsigndate5": xsigndate5,
        "xsignatory6": xsignatory6,
        "xsigndate6": xsigndate6,
        "xsignatory7": xsignatory7,
        "xsuperiorsp": xsuperiorsp,
        "xsigndate7": xsigndate7,
        "xstatus": xstatus,
        "xidsup": xidsup,
        "xcatitemacc": xcatitemacc,
        "xgroupcat": xgroupcat,
        "xassetitem": xassetitem,
        "xfagroup": xfagroup,
        "xfatype": xfatype,
        "xfacat": xfacat,
        "xprcstype": xprcstype,
        "xitemref": xitemref,
        "xsignreject": xsignreject,
        "xdatereject": xdatereject,
        "xnote1": xnote1,
        "xitemtype": xitemtype,
      };
}

// class Xsigndate1 {
//   Xsigndate1({
//     required this.date,
//     required this.timezoneType,
//     required this.timezone,
//   });
//
//   String date;
//   int timezoneType;
//   String timezone;
//
//   factory Xsigndate1.fromJson(Map<String, dynamic> json) => Xsigndate1(
//         date: json["date"],
//         timezoneType: json["timezone_type"],
//         timezone: json["timezone"],
//       );
//
//   Map<String, dynamic> toJson() => {
//         "date": date,
//         "timezone_type": timezoneType,
//         "timezone": timezone,
//       };
// }
